mod 'puppet/nginx', '1.0.0'
# dependencies for nginx
mod 'puppetlabs/concat'
mod 'puppetlabs/stdlib'
mod 'puppetlabs/translate'
mod 'puppetlabs/docker'
mod 'puppetlabs/apt'
mod 'puppetlabs/powershell'
mod 'puppetlabs/reboot'
mod 'dsctsg/dscagent'
